### PR TITLE
Fix plots

### LINKED ISSUE #2: Figure 2
I think that we should reorganize section (a) of this figure to the following layout: 

| histogram          | raw_neighbor_corr             |
|--------------------|-------------------------------|
| raw_num_bad_slices |  max_relative_translation     |

This is because I think that the text should first discuss the distribution of values, followed by a description of the relationship with the QC metrics. Also, I believe that the x axis label for the sub-plot with max_relative_translation is currently incorrect ("Expert QC rating"). 

If not too hard, it would be nice to also have the axis labels not be written in snake case.

### PR DESCRIPTION
**Pull request by richford**
Resolves #2 and standardizes other plots. Also converts to eLife style.

### CODE REVIEW

**Comment by richford** [comment]
Added commits to
- standardize all of the figure dimensions and fonts to match the font of the text.
- Change the style file to eLife's style
- Fix most of my remaining todo items

@arokem, I think this is ready for review

**Comment by arokem** [comment]
Comments: 

- In many figures the sub-plot labels occlude the top y tick label. Would it be easy to avoid this? For example, by moving the sub-plot labels to the top right in each of these? 
- I didn't notice this until now, but Figure 1 has some small text that says "HBN-POD2 Data Workflow". I believe you can remove that.

**Comment by richford** [comment]
Thanks @arokem, those comments should be resolved in the latest commit.

**Comment by arokem** [comment]
Looks great!

**Pull request merged**
